### ISSUE TITLE
Dynamic IP challenge.

### ISSUE THREAD

**Issue by Zoidberg2** [igniterealtime/openfire-pionturn-plugin#12]
For people that are running their servers in a dynamic IP environment using the Pionturn plugin for Openfire is a challenge.
every time the IP changes server admins will have to open the admin panel and update the IP manually on the Pionturn side.
this issue will be even bigger with the new release, requiring the users to re config everything in the External Service Discovery then going to the plugin to catch again the settings from the External Service Discovery and then reloading the plugin again.
Some comments about this made me believe that this mechanism that is  already implemented by Pionturn itself would solve this issue by looking up the DNS name:(https://github.com/pion/turn/issues/244). however i did not succeed in implementing this mechanism into the Pionturn binaries.
although this also could be solved by other ways for example something in your java code to do something like: check the external IP if the same do nothing, if changed then apply the new IP + reload the plugin? doing this like every 10 minutes? 
but it certainly also uses more resources and if an user actually have an static IP this would not even be necessary.

**Comment by deleolajide** [comment]
Code to resolve DNS to IP Address is straightforward.  

See  https://stackoverflow.com/questions/63498642/find-ip-address-by-domain-in-go

````
    ips, _ := net.LookupIP("google.com")
    
    for _, ip := range ips {
        if ipv4 := ip.To4(); ipv4 != nil {
            fmt.Println("IPv4: ", ipv4)
        }
    }
````

However, looking specifically at our use case where PionTurn is embedded in Openfire and is bound to the IP address on which Openfire is running, there is no benefit to doing this in PionTurn.  We only need to resolve before we start the PionTurn binary. If the Ip address changes, it means Openfire will also need to be restarted and PionTurn will be restarted with the correct IP address.

**Comment by deleolajide** [comment]
>issue will be even bigger with the new release, requiring the users to re config everything in the External Service Discovery then going to the plugin to catch again the settings from the External Service Discovery and then reloading the plugin again.

For Pionturn, the hostname specified in External Service Discovery, **MUST** match Openfire's hostname.

**Comment by deleolajide** [comment]
> if it is not the same then the script will set the new IP and reload/restart the turn server.

PionTurn plugin may not need to restart the pionturn server because it is listening to all interfaces (0.0.0.0) . best way to confirm this is to test it. 👍

**Comment by deleolajide** [comment]
As discussed, we now have DNS resolution happening both ways.  Openfire plugin will first resolve and pass both hostname and ipaddr to pionturn. Every time pionturn calls RelayAddress, it will resolve again with this. 
````
func resolveHostName(hostName string, ipaddress string) net.IP {	
    ips, _ := net.LookupIP(hostName)
    
    for _, ip := range ips {
        if ipv4 := ip.To4(); ipv4 != nil {
			return ip
        }
    }
	return net.ParseIP(ipaddress)
}
````
If it fails, it falls back on the ipaddr provided by openfire.
