### ISSUE TITLE
How to add it to openfire server.

### ISSUE THREAD

**Issue by BRUTme** [igniterealtime/openfire-pionturn-plugin#2]
Hello,
can u add a compilled functional plugin for download too and some enhance description? does it work with Conversations android app?

Thanx in Advance :)

Brut

**Comment by deleolajide** [comment]
> does it work with Conversations android app?

Yes. See 
https://discourse.igniterealtime.org/t/preparing-openfire-for-audio-video-calls-with-conversations/87828
https://discourse.igniterealtime.org/t/no-sound-using-ohun-plugin/89347/5?u=dele_olajide
https://github.com/igniterealtime/openfire-ohun-plugin

**Comment by akrherz** [comment]
There is a [download available](https://igniterealtime.org/projects/openfire/plugins.jsp) now from our website.  Closing this for now.
